name: CodeCov

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'  # Ajoutez cette ligne

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
          architecture: x64

      - name: Set up secrets
          run: echo "BDD_SERVEUR=$BDD_SERVEUR" >> $GITHUB_ENV echo "BDD_PORT=$BDD_PORT" >> $GITHUB_ENV echo "BDD_NOM=$BDD_NOM" >> $GITHUB_ENV

      - name: Build with Maven
        run: mvn clean install

      - name: Run Tests
        run: mvn test

      - name: Generate Jacoco Coverage Report
        run: mvn jacoco:report
        continue-on-error: true

      - name: Publish Jacoco Report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: target/site/jacoco

      - name: Publish Test Results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: target/surefire-reports

      - name: Upload to CodeCov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}